### ISSUE TITLE
Export/Backup grep console settings

### ISSUE THREAD

**Issue by mithereal** [krasa/GrepConsole#225]
**Is your feature request related to a problem? Please describe.**
Occasionally my ide will crash and/or i will need to reinstall and all my settings are lost leading to re-inserting

**Describe the solution you'd like**
Button to click or integration with sync settings

**Comment by viper7882** [comment]
Hi @krasa,

Thank you for supporting this wonderful plugin. I'm using it in PyCharm and in my experience of using it, it is working flawlessly.

I share the same sentiment where Grep Console Settings could be enhanced with both exported and imported functionality.

In case if you are looking for suggestion, those settings could either be exported into JSON or XML format and then re-imported as the same format. It should be trivial to implement.

Thank you for considering @mithereal and my feedback above.

**Comment by michaelkariv** [comment]
@viper7882 , You can export and import settings. It is impolemented, one might argue, the best way possible - using PyCharm (or IntelliJ IDEs in general) File/Manage IDE Settings/export.
You'll be prsented with options to export. Disable everything, then look up in the list of options 'GrepConsole'
The import is the the other way around. You choose import instead of export, and then point to the zip file and you'll see only GrepConsole checked in option. 

I might argue and suggest to @krasa to 1. document it 2. enable export and import rght from the UI of the grep console and 3. enable options of merge - where profiles (and I suggest you guys do use profile - it is terrific) from the imported settings are added, while old profiles retained, at least optionally.

**Comment by michaelkariv** [comment]
Just to illustrate my above points, couple of screenshots
![screen1 IDE emnu](https://user-images.githubusercontent.com/39742/202755796-74e56a15-97d2-4b21-8e6c-3b0c423d73e9.png)
![screen2- export options](https://user-images.githubusercontent.com/39742/202755835-85095609-27fd-46ac-891c-78a90bc28be8.png)

**Comment by viper7882** [comment]
Thanks the sharing, @michaelkariv. I didn't know such export settings available for PyCharm inclusive of Grep Console. @mithereal , I'm OK to get this issue closed for now.

**Comment by mithereal** [comment]
Ill close thx didnt know bout export either
