### ISSUE TITLE
Save/Load configuration to external file

### ISSUE THREAD

**Issue by OleksandrKucherenko** [krasa/GrepConsole#46]
Will be good to have ability to save and load configuration into external file (sharing inside the team members).

**Comment by krasa** [comment]
It should work. File | Export/Import Settings...
![image](https://cloud.githubusercontent.com/assets/1160875/7935049/af74337c-092d-11e5-9cb1-f7cbdd27267f.png)

**Comment by brcolow** [comment]
That will export the settings as a jar, which in my opinion is less than ideal. I way to export as plain-text XML or JSON (and have the GrepConsole plugin be able to import those settings) would be ideal as it would allow one to see the settings at a glance and edit them directly in a text editor. Putting this exported file in a projects root directory, so that other developers can immediately benefit, would be the ideal situation in my opinion.

**Comment by krasa** [comment]
that jar only bundles what is already in .IntelliJIdea14/config/options/GrepConsole.xml so we could do anything with it. 
The reason why it is not in the project dir automatically is that it is a global config. I could introduce a project specific settings, but I never actually needed it that much...
Or maybe I could implement some fine grained import, which would not replace your config, but only added new items, and some nice action to export the config.

**Comment by OleksandrKucherenko** [comment]
thanks.
