### ISSUE TITLE
Is it possible to fire off a notification on match?

### ISSUE THREAD

**Issue by bcosynot** [krasa/GrepConsole#97]
I would love to be able to see a notification if a substring is matched on the console. Is it possible to do that with the current version?

**Comment by krasa** [comment]
Nope.

**Comment by benjwarner** [comment]
Yes, that would be very cool.

I'm working on an app at work that involves running several servers (in Intellij) at the same time.  At any time one of them might match a 'GrepConsole' pattern, and would be awesome if they appeared as a notification, otherwise I have to go 'hunting' for errors when I think something is wrong.

**Comment by krasa** [comment]
Done by  #66
